title: Hello, world! I'm Nuno Cancelo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://masterzdran.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nuno Cancelo # add your name
author-img: nuno-cancelo.jpeg # add your photo
about-author: I am a Software Engineer, eager to learn and even more to share knowledge.  # add description
social-twitter: masterzdran # add your Twitter handle
social-github: masterzdran # add your Github handle
social-linkedin: nunocancelo # add your Linkedin handle
social-email: nuno.cancelo@gmail.com # add your Email address

# Disqus
discus-identifier: masterzdran-github-io # add your discus identifier

# Tracker
analytics: UA-148007585-1 # Google Analytics
adsense: ca-pub-4816532281628693 # Google Adsense

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
