--- #------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Jekyll serves Github Pages locally
# ... because I'm a developer and I too lazy.
version: "3.0"
services:
  Jekyll:
    image: starefossen/github-pages:198
    container_name: JekyllServer
    ports:
      - 50061:4000
    volumes:
      - .:/usr/src/app
    tty: true
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Europe/Lisbon
